version: '3.8'

services:
    client:
     container_name: frontend
     build:
       context: ./client/
     command: yarn run start
     ports:
       - 8081:8081
     volumes:
       - ./client:/usr/src/app
       - common:/apk
     depends_on:
       - dev
     restart: unless-stopped
    dev:
      container_name: api
      build:
        context: ./server/
      command: yarn run start
      ports:
        - 8080:8080
        - 9229:9229
      volumes:
        - ./server:/usr/src/app
      depends_on:
        - postgres
      restart: unless-stopped
    postgres:
      image: postgres:10.4
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db
      ports:
        - "35000:5432"
      volumes:
        - ./postgres:/var/lib/postgresql/data
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      restart: always
    postgres_admin:
      image: dpage/pgadmin4:4.28
      depends_on:
        - postgres
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: password
      ports:
        - "5050:80"
    app:
      build:
        context: ./app/area/
      depends_on:
        - client
      volumes:
        - common:/apk

volumes:
  common: